### ISSUE TITLE
usage?

### ISSUE THREAD

**Issue by srsarcasmo** [ModusCreateOrg/cordova-swift-plugin-example#1]
no exist demo from usage

**Comment by emimuresan** [comment]
Thank you for filing this issue! :heart: 

We no longer maintain this repository, but we continue to work on the most cutting-edge open source projects. You can find amazing solutions and ideas on the [Modus Labs](https://labs.moduscreate.com?utm_source=github&utm_medium=issues&utm_campaign=deprecated) website.
