### ISSUE TITLE
ERROR: Method 'echo:' not defined in Plugin 'ModusEchoSwift

### ISSUE THREAD

**Issue by narendra-ct** [ModusCreateOrg/cordova-swift-plugin-example#2]
Hello,

I tried the plugin with swift 4.0 and xcode 9.2, but i get an error says "ERROR: Method 'echo:' not defined in Plugin 'ModusEchoSwift'".

Please help me on this.

Thanks,
Narendra

**Comment by ternblom** [comment]
Hello,

I am using xCode 10.1, this is an update of this code.

`

    @objc(ModusEchoSwift)    
    class ModusEchoSwift : CDVPlugin {
     
    func echo(_ command: CDVInvokedUrlCommand) {
   
    var pluginResult = CDVPluginResult(status: CDVCommandStatus_ERROR)

    let msg = command.arguments[0] as? String ?? ""
    
    if msg.count > 0 {
      let toastController: UIAlertController = 
        UIAlertController(title: "",  message: msg, preferredStyle: .alert)
        self.viewController?.present(toastController, animated: true, completion: nil)
        
        DispatchQueue.main.asyncAfter(deadline: .now() + .milliseconds(2000)) {
            toastController.dismiss(animated: true, completion: nil)
        }

        pluginResult = CDVPluginResult(
            status: CDVCommandStatus_OK,
            messageAs: msg
        )
    }

    self.commandDelegate!.send(pluginResult, callbackId: command.callbackId) }}`

**Comment by emimuresan** [comment]
Thank you for filing this issue! :heart: 

We no longer maintain this repository, but we continue to work on the most cutting-edge open source projects. You can find amazing solutions and ideas on the [Modus Labs](https://labs.moduscreate.com?utm_source=github&utm_medium=issues&utm_campaign=deprecated) website.
